### PR TITLE
Fixed compatibility issue with XL Deploy 8.5 - for xld-websphere-portal plugin

### PR DESCRIPTION
**Pull request by ioanaf06**
- removed from DirectortDiff class unused import for deprecated class InputSupplier.
    This class was removed from later versions of guava library,
    which breaks the contract with newer integrations.

### CODE REVIEW

**Comment by ioanaf06** [comment]
@ravan @jdewinne Can you please review the changes and make a release of the plugin? We need to add this to xld-websphere-portal plugin in order to function in XL Deploy 8.5. Thanks!

**Comment by vlussenburg** [comment]
Thanks for the pull request - we need to update some plumbing since the project is not building right now but we'll merge and release overthere-pylib ASAP.

**Comment by ioanaf06** [comment]
Hello,
After you manage to release this one can you please update the version in xebialabs-community/xld-websphere-portal-plugin

| 
| 
| 
|  |  |

 |

 |
| 
|  | 
xebialabs-community/xld-websphere-portal-plugin

Websphere Portal Plugin for XL Deploy. Contribute to xebialabs-community/xld-websphere-portal-plugin development...
 |

 |

 |


and release it also? 
This is the plugin we need (at Rabobank) in order to deploy the applications in WebSphere Portal, using XL Deploy 8.5.
Many thanks!Ioana
Ioana Faloba | Java Developer | Mobile: (004) 0748 63 32 23 | ioana_f06@gmail.com 

    On Tuesday, December 18, 2018, 6:51:14 PM GMT+2, Vincent Lussenburg <notifications@github.com> wrote:  
 
 
Thanks for the pull request - we need to update some plumbing since the project is not building right now but we'll merge and release overthere-pylib ASAP.

**Comment by ioanaf06** [comment]
You're welcome!
 After you manage to release this one can you please update its version in https://github.com/xebialabs-community/xld-websphere-portal-plugin and release that one also ? Many thanks!

**Pull request merged**
